import { MigrationInterface, QueryRunner } from "typeorm";

export class AddScreenshotTimestamp1770889411258 implements MigrationInterface {
    name = 'AddScreenshotTimestamp1770889411258'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "fk_sessions_organization"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "fk_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "fk_sessions_project"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "fk_users_organization"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "fk_projects_organization"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "fk_projects_creator"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP CONSTRAINT "fk_summaries_organization"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP CONSTRAINT "fk_summaries_user"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "fk_alerts_user"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "fk_activity_logs_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_last_activity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_org_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_activity_logs_session_timestamp"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "uq_users_org_email"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP CONSTRAINT "uq_summaries_user_date"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD "organizationId" uuid`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD "projectId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "organizationId" uuid`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "organizationId" uuid`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "creatorId" uuid`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD "organizationId" uuid`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "sessionId" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."session_status_enum" RENAME TO "session_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."work_sessions_status_enum" AS ENUM('active', 'stopped')`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "status" TYPE "public"."work_sessions_status_enum" USING "status"::"text"::"public"."work_sessions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."session_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "last_activity_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "last_activity_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum" RENAME TO "user_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'manager', 'employee')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'employee'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status_enum" RENAME TO "user_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."users_status_enum" USING "status"::"text"::"public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."alert_type_enum" RENAME TO "alert_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."alerts_type_enum" AS ENUM('idle', 'overtime')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "type" TYPE "public"."alerts_type_enum" USING "type"::"text"::"public"."alerts_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alert_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."activity_type_enum" RENAME TO "activity_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activity_logs_activity_type_enum" AS ENUM('active', 'idle')`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "activity_type" TYPE "public"."activity_logs_activity_type_enum" USING "activity_type"::"text"::"public"."activity_logs_activity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_type_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_9964bed879b02c7357218760ca" ON "work_sessions" ("organization_id", "start_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc1733a6fc6da48eb5e545de2c" ON "work_sessions" ("user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_04402eb4cf7be16f6cc5e5f078" ON "users" ("organization_id", "email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2bec94b8d146beda9ec7c984e4" ON "daily_summaries" ("user_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f02668456651f0f3a8e24a539" ON "activity_logs" ("session_id", "timestamp") `);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "FK_d0e4b9129617a166a308b098ef6" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "FK_7f1bcfe98595e0a130117224ddf" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "FK_a7a790065ee6b574355dc15f61d" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_f3d6aea8fcca58182b2e80ce979" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_eec93fd979bdcf5a0141da324d6" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_1beb66d6bdd694692f8eb9881b4" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD CONSTRAINT "FK_3d1912f0050c5d2e48256044074" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD CONSTRAINT "FK_1e32abf6645290616cbad2b5f52" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_f2678f7b11e5128abbbc4511906" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_67d411510fb2cb28df0463850d6" FOREIGN KEY ("sessionId") REFERENCES "work_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_67d411510fb2cb28df0463850d6"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_f2678f7b11e5128abbbc4511906"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP CONSTRAINT "FK_1e32abf6645290616cbad2b5f52"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP CONSTRAINT "FK_3d1912f0050c5d2e48256044074"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_1beb66d6bdd694692f8eb9881b4"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_eec93fd979bdcf5a0141da324d6"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_f3d6aea8fcca58182b2e80ce979"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "FK_a7a790065ee6b574355dc15f61d"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "FK_7f1bcfe98595e0a130117224ddf"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP CONSTRAINT "FK_d0e4b9129617a166a308b098ef6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f02668456651f0f3a8e24a539"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bec94b8d146beda9ec7c984e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04402eb4cf7be16f6cc5e5f078"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc1733a6fc6da48eb5e545de2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9964bed879b02c7357218760ca"`);
        await queryRunner.query(`CREATE TYPE "public"."activity_type_enum_old" AS ENUM('active', 'idle')`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "activity_type" TYPE "public"."activity_type_enum_old" USING "activity_type"::"text"::"public"."activity_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."activity_logs_activity_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."activity_type_enum_old" RENAME TO "activity_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."alert_type_enum_old" AS ENUM('idle', 'overtime')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "type" TYPE "public"."alert_type_enum_old" USING "type"::"text"::"public"."alert_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."alerts_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."alert_type_enum_old" RENAME TO "alert_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum_old" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."user_status_enum_old" USING "status"::"text"::"public"."user_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status_enum_old" RENAME TO "user_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum_old" AS ENUM('admin', 'manager', 'employee')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_enum_old" USING "role"::"text"::"public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'employee'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum_old" RENAME TO "user_role_enum"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "last_activity_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "last_activity_at" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."session_status_enum_old" AS ENUM('active', 'stopped')`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "status" TYPE "public"."session_status_enum_old" USING "status"::"text"::"public"."session_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."work_sessions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."session_status_enum_old" RENAME TO "session_status_enum"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "creatorId"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP COLUMN "projectId"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "work_sessions" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD CONSTRAINT "uq_summaries_user_date" UNIQUE ("user_id", "date")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "uq_users_org_email" UNIQUE ("organization_id", "email")`);
        await queryRunner.query(`CREATE INDEX "idx_activity_logs_session_timestamp" ON "activity_logs" ("session_id", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "idx_users_org_email" ON "users" ("organization_id", "email") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_last_activity" ON "work_sessions" ("last_activity_at") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_user_status" ON "work_sessions" ("user_id", "status") `);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "fk_activity_logs_session" FOREIGN KEY ("session_id") REFERENCES "work_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "fk_alerts_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD CONSTRAINT "fk_summaries_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_summaries" ADD CONSTRAINT "fk_summaries_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_creator" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "fk_users_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "fk_sessions_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "fk_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_sessions" ADD CONSTRAINT "fk_sessions_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
